<?php
/** @var \Hoan\Student\Block\Listing $block */
?>

<h3 style="text-align: center;">Students List</h3>
<table class="table table-bordered table-striped table-hover table-reponsive scroll">
    <thead>
        <a href="<?= $block->escapeHtml($block->getBaseUrl()); ?>student/index/create" class="btn btn-primary btn-xs pull-right">Create New Student</a>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Birthday</th>
            <th>Image</th>
            <th>Creared At</th>
            <th>Updated At</th>
            <th colspan="2">Action</th>
        </tr>
    </thead>
    <?php
    $students = $block->getStudents()->getItems();
    foreach ($students as $student) {
        echo "<tr style=\"border: 1px solid #dddddd; text-align: left; padding: 8px;\">";
        echo "<td>" . $block->escapeHtml(__($student->getStudentId())) . "</td>";
        echo "<td>" . $block->escapeHtml(__($student->getStudentName())) . "</td>";
        echo "<td>" . $block->escapeHtml(__(date('Y-m-d', strtotime($student->getStudentBirthday())))) . "</td>";
        echo "<td>" . $block->escapeHtml(__($student->getStudentImg())) . "</td>";
        echo "<td>" . $block->escapeHtml(__($student->getCreatedAt())) . "</td>";
        echo "<td>" . $block->escapeHtml(__($student->getUpdatedAt())) . "</td>";
        echo '<td><a href="' . $block->escapeHtml(__($block->getBaseUrl())) . 'student/index/edit/student_id/' .
            $block->escapeHtml(__($student->getStudentId())) . '" class="btn btn-primary btn-xs pull-right">Edit</a></td>';
        echo '<td><a href="' . $block->escapeHtml(__($block->getBaseUrl())) . 'student/index/delete/student_id/' .
            $block->escapeHtml(__($student->getStudentId())) . '" class="btn btn-primary btn-xs pull-right">Delete</a></td>';
        echo "</tr>";
    }
    ?>
</table>